# Generated by Django 3.1.1 on 2020-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='path',
            field=models.CharField(default=1, max_length=500, verbose_name='Путь к папке'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disk',
            name='allSize',
            field=models.IntegerField(default=5000000000, verbose_name='Всё место на диске пользователя'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Занятое на диске место'),
        ),
    ]
