# Generated by Django 3.1.1 on 2020-09-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200925_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathToFile', models.CharField(max_length=1000, verbose_name='Путь к общедоступному файлу')),
                ('url', models.CharField(max_length=1000, verbose_name='Набор символов покоторому можно будет получить доступ к файлу')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disk', verbose_name='Диск, на котором хранится файл')),
            ],
            options={
                'verbose_name': 'Общедоступный файл',
                'verbose_name_plural': 'Общедоступные файлы',
            },
        ),
    ]
