# Generated by Django 3.1 on 2020-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200824_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='file',
        ),
        migrations.AddField(
            model_name='disk',
            name='path',
            field=models.CharField(default='/', max_length=500, verbose_name='Путь к папке'),
            preserve_default=False,
        ),
    ]
