# Generated by Django 3.1.1 on 2020-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201026_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='theme',
            field=models.CharField(default='light', max_length=20, verbose_name='Название темы'),
        ),
    ]
